### ISSUE TITLE
Unexpected Token ...

### ISSUE THREAD

**Issue by luke-unifymonitor** [AnomalyInnovations/serverless-es7#8]
Hi,

Following the instructions from the README.md I get the error

Unexpected Token ...

Any ideas?

serverless --version
1.22.0

```
serverless install --url https://github.com/AnomalyInnovations/serverless-es7 --name my-project
cd my-project
npm install
serverless invoke local --function hello -l
```

```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command webpack:invoke
Serverless: Load command webpack:watch
Serverless: Load command webpack:serve
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: Invoke invoke:local
 
  Syntax Error -------------------------------------------
 
  Unexpected token ...
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token ...
/home/luke/Documents/FOO/my-project/webpack.config.js:6
  ...acc,
  ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at ServerlessWebpack.validate (/home/luke/Documents/FOO/my-project/node_modules/serverless-webpack/lib/validate.js:102:28)
    at ServerlessWebpack.tryCatcher (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/luke/Documents/FOO/my-project/node_modules/bluebird/js/release/async.js:17:14)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:358:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:389:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:39:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.0
     Serverless Version:     1.22.0
 
```

**Comment by luke-unifymonitor** [comment]
Compared against previous versions, it looks like the README.md should be updated to read

`serverless webpack invoke --function hello`

rather than

`serverless invoke local --function hello -l`

**Comment by jayair** [comment]
@luke-unifymonitor I'm not sure what is going on here but have you updated `serverless-webpack` to v3 (https://github.com/serverless-heaven/serverless-webpack/releases/tag/v3.0.0)?

This is also why we are now using `serverless invoke local` instead of `serverless webpack invoke`.

**Comment by luke-unifymonitor** [comment]
Thanks @jayair.  I haven't got serverless-webpack installed globally.  

I just do a `serverless install --url https://github.com/AnomalyInnovations/serverless-es7 --name my-project`

The package.json it creates is as below which has `"serverless-webpack": "^3.0.0"` in devDependencies. 

```
{
  "name": "my-test",
  "version": "1.1.0",
  "description": "A starter project for the Serverless Framework with ES7 support",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/AnomalyInnovations/serverless-es7.git"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "serverless-webpack": "^3.0.0",
    "webpack": "^3.0.0",
    "webpack-node-externals": "^1.6.0"
  },
  "dependencies": {
    "babel-runtime": "^6.23.0",
    "source-map-support": "^0.4.14"
  }
}
```

**Comment by jayair** [comment]
@luke-unifymonitor Yup that should work. You should now be able to run `serverless invoke local --function hello` and it should run your function locally.

**Comment by radelcom** [comment]
I am also getting similar error message with just `sls deploy` and not specific function. I was digging around and narrowed it down. It seems like dependent on which ever node version I am using. I am using [nvm](https://github.com/creationix/nvm) as my node version manager. If I use node v6.10.3, I get this issue and if I switched to node v8.4.0, all goes away and deploys successfully. 

I guess question is, is it ok to use node v8.4.0 development and wont have impact to the actual AWS supported node v6.10 version when serverless is deployed?

Any input is greatly appreciated. tx in advance!

**Comment by luke-unifymonitor** [comment]
@jayair should work.....alas, it doesn't. Still getting the same error message.

` Unexpected token ...`

I'm on node 7.10.0

**Comment by jayair** [comment]
@radelcom @luke-unifymonitor @jackmusick Thanks for all the details. Yeah I should switch the code around and not assume folks are running a higher version of Node. I'll push an update soon.

**Comment by jayair** [comment]
@radelcom @luke-unifymonitor @jackmusick Just pushed an update. Can you guys try again?

**Comment by luke-unifymonitor** [comment]
@jayair - That's sorted it for me.  Thanks very much.

**Comment by jayair** [comment]
Great!

@radelcom @jackmusick If you guys can confirm, then we'll close the issue.

**Comment by radelcom** [comment]
@jayair - looks good here now too. although I switched my implementation to use [babel-plugin-source-map-support](https://github.com/chocolateboy/babel-plugin-source-map-support). Now I dont need the `_webpack` folder with `include.js` anymore.

my `.babelrc` looks like this now
```
{
  "plugins": ["source-map-support", "transform-runtime"],
  "presets": ["es2015", "stage-3"]
}
```
 and `webpack.config.js`
```
const slsw          = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [{
      test: /\.js$/,
      loaders: ['babel-loader', 'eslint-loader'],
      include: __dirname,
      exclude: /node_modules/
    }]
  }
};
```

**Comment by jayair** [comment]
@radelcom Oh that looks good. I'm going to try that out.

**Comment by jayair** [comment]
@radelcom Just updated the repo to use the babel source map plugin. Thanks for the feedback guys.

Closing this issue.
